name: Build package

on:
    push:
        branches: ["main"]
    pull_request_target:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Cache LLVM and Clang
              id: cache-llvm
              uses: actions/cache@v2
              with:
                  path: |
                      C:/Program Files/LLVM
                      ./llvm
                  key: llvm-15
            - name: Install LLVM and Clang
              uses: KyleMayes/install-llvm-action@v1
              with:
                  version: 15
                  cached: ${{ steps.cache-llvm.outputs.cache-hit }}
            - uses: pnpm/action-setup@v2
              with:
                  version: 7
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"
                  cache: "pnpm"
            - name: Install NPM dependencies
              run: pnpm install --frozen-lockfile
            - name: Build package
              run: pnpm build
